components:
  checkout:
    enabled: true
    imageOverride:
      repository: sherlocksai/otel-demo-checkout
      tag: latest
      pullPolicy: Always
  product-catalog:
    enabled: true
    imageOverride:
      repository: sherlocksai/otel-demo-product-catalog
      tag: latest
      pullPolicy: Always
    envOverrides:
      - name: NEW_RELIC_LICENSE_KEY
        valueFrom:
          secretKeyRef:
            name: new-relic-license-key
            key: license-key
  recommendation:
    enabled: true
    imageOverride:
      repository: sherlocksai/otel-demo-recommendation
      tag: latest
      pullPolicy: Always
  cart:
    enabled: true
    imageOverride:
      repository: sherlocksai/otel-demo-cart
      tag: latest
      pullPolicy: Always

global:
  namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1

prometheus:
  server:
    resources:
      requests:
        memory: "300Mi"
        cpu: "500m"
      limits:
        memory: "400Mi"
        cpu: "1000m"
