name: Build Dotnet Services

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/cart/**'
      - '.github/workflows/build-cart-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/cart/**'

env:
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_IMAGE_NAME: sherlocksai/otel-demo

jobs:
  build:
    name: Build Cart Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd src/cart
          dotnet restore

      - name: Build
        run: |
          cd src/cart
          dotnet build --no-restore

      - name: Test
        run: |
          cd src/cart
          dotnet test --no-build

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/cart/src/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-cart:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-cart:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-cart:buildcache,mode=max