name: Publish Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_IMAGE_NAME: sherlocksai/opentelemetry-demo

jobs:
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKERHUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push checkout service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/checkout/Dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-checkout:latest
        cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-checkout:buildcache
        cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-checkout:buildcache,mode=max

    - name: Build and push product-catalog service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/product-catalog/Dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-product-catalog:latest
        cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-product-catalog:buildcache
        cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-product-catalog:buildcache,mode=max

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/frontend/Dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:latest
        cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:buildcache
        cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:buildcache,mode=max
