name: Build Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'src/frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/frontend/**'

env:
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_IMAGE_NAME: sherlocksai/opentelemetry-demo

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd src/frontend
          npm ci

      - name: Lint
        run: |
          cd src/frontend
          npm run lint

      - name: Type check
        run: |
          cd src/frontend
          npm run type-check

      - name: Build
        run: |
          cd src/frontend
          npm run build

      - name: Run tests
        run: |
          cd src/frontend
          npm run test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend:buildcache,mode=max

      - name: Build Cypress Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/frontend/Dockerfile.cypress
          push: true
          tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend-cypress:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend-cypress:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-frontend-cypress:buildcache,mode=max
