name: Build Go Services

on:
  push:
    branches: [ main ]
    paths:
      - 'src/checkout/**'
      - 'src/product-catalog/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/checkout/**'
      - 'src/product-catalog/**'

env:
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_IMAGE_NAME: sherlocksai/opentelemetry-demo

jobs:
  build:
    name: Build Go Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [checkout, product-catalog]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go and protoc-gen-go-grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Generate protobuf
      run: |
        cd src/${{ matrix.service }}
        go generate

    - name: Build
      run: |
        cd src/${{ matrix.service }}
        go build -v ./...

    - name: Test
      run: |
        cd src/${{ matrix.service }}
        go test -v ./...

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKERHUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: src/${{ matrix.service }}
        push: true
        tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE_NAME }}-${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 